name: Upload to Localazy
on: 
  push:
    paths: 
      - 'locales/en.json'

jobs:
  localazy-upload:
    name: Upload locales to Localazy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v1

      - name: Upload locales to Localazy 🗺️
        uses: localazy/upload@v1
        with:
          read_key: ${{ secrets.LOCALAZY_READ_KEY }}
          write_key: ${{ secrets.LOCALAZY_WRITE_KEY }}